class OrigamiModel {
  final int id;
  final String title;
  final String category;
  final int difficulty; // 1-5
  final int stepsCount;
  final String timeEstimate;
  final String description;
  final String imagePath;
  final List<String> steps;
  final List<String> stepImages;
  final List<String> stepDiagrams;
  final String? videoTutorial;
  bool isFavorite;
  int currentStep; // 0 nếu chưa gấp, > 0 biểu thị bước đang gấp dở
  bool isCompleted;

  OrigamiModel({
    required this.id,
    required this.title,
    required this.category,
    required this.difficulty,
    required this.stepsCount,
    required this.timeEstimate,
    required this.description,
    required this.imagePath,
    required this.steps,
    required this.stepImages,
    this.stepDiagrams = const [],
    this.videoTutorial,
    this.isFavorite = false,
    this.currentStep = 0,
    this.isCompleted = false,
  });
}

class MockData {
  static List<OrigamiModel> models = [
    OrigamiModel(
      id: 1,
      title: 'Chim Hạc Giấy',
      category: 'Động vật',
      difficulty: 2,
      stepsCount: 21,
      timeEstimate: '10 phút',
      description: 'Mẫu gấp chim hạc giấy truyền thống của Nhật Bản, biểu tượng của sự hòa bình và may mắn.',
      imagePath: 'assets/images/Crane/Cover.png',
      videoTutorial: 'assets/images/Crane/Tutorial-Crane-Origami.mp4',
      steps: [
        'Đặt mặt trắng của giấy hướng lên trên. Gấp đôi tờ giấy theo chiều dọc, sau đó mở ra.',
        'Gấp đôi tờ giấy theo chiều ngang và mở ra. Sau đó, lật mặt sau tờ giấy.',
        'Gấp và mở ra theo cả hai đường chéo.',
        'Xoay 45 độ theo chiều kim đồng hồ, sau đó lật mặt sau.',
        'Thu gọn các nếp gấp đã tạo để hình thành một hình vuông nhỏ (Square Base).',
        'Gấp mép hai bên góc mở vào đường giữa, sau đó gấp góc đỉnh tam giác xuống lấy nếp rồi mở ra toàn bộ.',
        'Kéo mép dưới của lớp giấy trên cùng lên theo nếp gấp bước 6 để tạo cánh hoa đào (Petal Fold).',
        'Lật mặt sau và lặp lại thao tác tương tự như bước 6 và 7.',
        'Gấp cánh đỉnh bên phải sang bên trái. Thực hiện tương tự với mặt sau.',
        'Gấp cánh dưới lên trên. Lặp lại với mặt sau.',
        'Gấp mép trái của cánh trên cùng xuống trùng với mép đáy.',
        'Gấp mép đáy của cánh trên cùng vào mép trái của hình tam giác.',
        'Gấp đôi cánh vừa tạo bằng cách đưa mép trên trùng mép dưới.',
        'Mở rộng và kéo cánh hạc vừa gấp xuôi xuống dưới.',
        'Gấp ngược lên theo đường mép phía sau.',
        'Gấp cánh hạc ngược lên trên trở lại.',
        'Gấp đôi cánh hạc sao cho mép trên trùng với mép dưới.',
        'Lặp lại toàn bộ các bước từ 11 đến 17 cho cánh hạc ở mặt bên kia.',
        'Gấp đôi cánh phía trên bên trái ra phía sau (Mountain fold). Lặp lại với cánh bên kia.',
        'Gấp ngược trong (Inside reverse fold) góc nhọn bên trái xuống dưới để tạo hình đầu và mỏ hạc.',
        'Nhẹ nhàng kéo cánh xếp nếp ra hai bên để tạo dáng cánh, kéo nhẹ đuôi hạc ra sau để hoàn thiện.'
      ],
      stepImages: [
        'assets/images/Crane/origami-sitting-crane-paper-fold-step-1.jpg',
        'assets/images/Crane/origami-sitting-crane-paper-fold-step-2.jpg',
        'assets/images/Crane/origami-sitting-crane-paper-fold-step-3.jpg',
        'assets/images/Crane/origami-sitting-crane-paper-fold-step-4.gif',
        'assets/images/Crane/origami-sitting-crane-paper-fold-step-5.gif',
        'assets/images/Crane/origami-sitting-crane-paper-fold-step-6.jpg',
        'assets/images/Crane/origami-sitting-crane-video-step-7.mp4',
        'assets/images/Crane/origami-sitting-crane-paper-fold-step-8.gif',
        'assets/images/Crane/origami-sitting-crane-video-step-9.mp4',
        'assets/images/Crane/origami-sitting-crane-video-step-10.mp4',
        'assets/images/Crane/origami-sitting-crane-paper-fold-step-11.jpg',
        'assets/images/Crane/origami-sitting-crane-paper-fold-step-12.jpg',
        'assets/images/Crane/origami-sitting-crane-paper-fold-step-13.jpg',
        'assets/images/Crane/origami-sitting-crane-paper-fold-step-14.jpg',
        'assets/images/Crane/origami-sitting-crane-paper-fold-step-15.jpg',
        'assets/images/Crane/origami-sitting-crane-paper-fold-step-16.jpg',
        'assets/images/Crane/origami-sitting-crane-paper-fold-step-17.jpg',
        'assets/images/Crane/origami-sitting-crane-video-step-18.mp4',
        'assets/images/Crane/origami-sitting-crane-video-step-19.mp4',
        'assets/images/Crane/origami-sitting-crane-video-step-20.mp4',
        'assets/images/Crane/origami-sitting-crane-video-step-21.mp4'
      ],
      stepDiagrams: [
        'assets/images/Crane/origami-sitting-crane-diagram-step-1.jpg',
        'assets/images/Crane/origami-sitting-crane-diagram-step-2.jpg',
        'assets/images/Crane/origami-sitting-crane-diagram-step-3.jpg',
        'assets/images/Crane/origami-sitting-crane-diagram-step-4.jpg',
        'assets/images/Crane/origami-sitting-crane-diagram-step-5.jpg',
        'assets/images/Crane/origami-sitting-crane-diagram-step-6.jpg',
        'assets/images/Crane/origami-sitting-crane-diagram-step-7.jpg',
        'assets/images/Crane/origami-sitting-crane-diagram-step-8.jpg',
        'assets/images/Crane/origami-sitting-crane-diagram-step-9.jpg',
        'assets/images/Crane/origami-sitting-crane-diagram-step-10.jpg',
        'assets/images/Crane/origami-sitting-crane-diagram-step-11.jpg',
        'assets/images/Crane/origami-sitting-crane-diagram-step-12.jpg',
        'assets/images/Crane/origami-sitting-crane-diagram-step-13.jpg',
        'assets/images/Crane/origami-sitting-crane-diagram-step-14.jpg',
        'assets/images/Crane/origami-sitting-crane-diagram-step-15.jpg',
        'assets/images/Crane/origami-sitting-crane-diagram-step-16.jpg',
        'assets/images/Crane/origami-sitting-crane-diagram-step-17.jpg',
        'assets/images/Crane/origami-sitting-crane-diagram-step-18.jpg',
        'assets/images/Crane/origami-sitting-crane-diagram-step-19.jpg',
        'assets/images/Crane/origami-sitting-crane-diagram-step-20.jpg',
        'assets/images/Crane/origami-sitting-crane-diagram-step-21.jpg'
      ],
      currentStep: 0,
    ),
    OrigamiModel(
      id: 2,
      title: 'Thuyền Giấy',
      category: 'Đồ vật',
      difficulty: 1,
      stepsCount: 8,
      timeEstimate: '3 phút',
      description: 'Mẫu gấp thuyền giấy cổ điển cực kỳ đơn giản và quen thuộc với tuổi thơ.',
      imagePath: 'assets/images/Boat/Cover.png',
      videoTutorial: 'assets/images/Boat/Tutorial Boat Origami.mp4',
      steps: [
        'Gấp đôi tờ giấy hình chữ nhật theo chiều ngang, miết nhẹ lấy nếp.',
        'Gấp hai góc phía trên vào nếp giữa tạo thành hình tam giác nhọn ở đỉnh.',
        'Gập phần mép giấy hình chữ nhật thừa ở dưới lên trên ở cả hai mặt.',
        'Gấp các góc nhỏ thừa ở mép vào trong ôm lấy hình tam giác ở cả 2 bên.',
        'Mở rộng lòng tam giác từ phía dưới và ép dẹt lại thành hình vuông.',
        'Gập góc dưới của hình vuông ngược lên trên đỉnh ở cả hai mặt để tạo hình tam giác mới.',
        'Mở rộng lòng hình tam giác thêm một lần nữa và ép dẹt lại thành hình vuông nhỏ.',
        'Nhẹ nhàng kéo hai góc nhọn bên hông ra hai bên, miết phẳng để tạo hình chiếc thuyền.'
      ],
      stepImages: [
        'assets/images/Boat/origami-boat-paper-fold-step-1-.jpg',
        'assets/images/Boat/origami-boat-paper-fold-step-2-.jpg',
        'assets/images/Boat/origami-boat-step-3-paper-fold-edited.jpg',
        'assets/images/Boat/origami-boat-step-4-paper-fold.jpg',
        'assets/images/Boat/origami-boat-step-5-paper-fold.jpg',
        'assets/images/Boat/origami-boat-step-6-paper-fold.mp4',
        'assets/images/Boat/origami-boat-step-7-paper-fold.jpg',
        'assets/images/Boat/origami-boat-step-8-paper-fold.mp4'
      ],
      stepDiagrams: [
        'assets/images/Boat/Traditional-Origami-Boat-Diagram-step-1.jpg',
        'assets/images/Boat/Traditional-Origami-Boat-Diagram-step-2.jpg',
        'assets/images/Boat/Traditional-Origami-Boat-Diagram-step-3.jpg',
        'assets/images/Boat/Traditional-Origami-Boat-Diagram-step-4.jpg',
        'assets/images/Boat/Traditional-Origami-Boat-Diagram-step-5.jpg',
        'assets/images/Boat/Traditional-Origami-Boat-Diagram-step-6.jpg',
        'assets/images/Boat/Traditional-Origami-Boat-Diagram-step-7.jpg',
        'assets/images/Boat/Traditional-Origami-Boat-Diagram-step-8.jpg'
      ],
      currentStep: 0,
    ),
    OrigamiModel(
      id: 3,
      title: 'Chuồn Chuồn Giấy',
      category: 'Động vật',
      difficulty: 4,
      stepsCount: 17,
      timeEstimate: '15 phút',
      description: 'Mẫu gấp chuồn chuồn tinh xảo với cánh rộng và thân dài, đòi hỏi sự kiên nhẫn.',
      imagePath: 'assets/images/Dragon/Cover.png',
      videoTutorial: 'assets/images/Dragon/ORIGAMI-DRAGONFLY-Tutorial.mp4',
      steps: [
        'Bắt đầu với tờ giấy hình vuông. Gấp chéo hai bên để tạo nếp gấp hình chữ X.',
        'Gấp đôi tờ giấy theo chiều ngang và dọc để tạo nếp gấp chữ thập (+).',
        'Lật giấy lại, gập bốn góc vào điểm tâm chính giữa (Blintz fold).',
        'Mở bốn góc vừa gập ra trở lại hình vuông ban đầu.',
        'Thu gọn các mép giấy theo các đường nếp đã tạo thành hình vuông nhỏ (Square Base).',
        'Gập hai mép dưới của lớp giấy trên cùng vào đường nếp giữa.',
        'Gập góc nhọn đỉnh xuống dưới rồi mở ra lấy nếp gấp.',
        'Kéo mép dưới lên tạo cánh hoa đào (Petal fold) dẹt phẳng.',
        'Lật mặt sau và lặp lại thao tác tạo cánh hoa đào tương tự.',
        'Gấp hai góc nhọn phía trên xuôi xuống để tạo hình đôi cánh dưới.',
        'Gập góc nhọn trên cùng xuống dưới.',
        'Gập ngược bên trong đuôi chuồn chuồn hướng xuống để tạo thân dài.',
        'Gấp cánh chuồn chuồn chếch ra ngoài sao cho vuông góc với thân.',
        'Kéo nhẹ đầu cánh tạo độ cong tự nhiên.',
        'Gấp mép hai bên hông của phần đuôi vào trong để thân chuồn chuồn thon gọn.',
        'Bẻ nhẹ phần đầu về phía sau để tạo hình mắt chuồn chuồn.',
        'Điều chỉnh cánh chuồn chuồn phẳng đều, uốn nhẹ thân để hoàn chỉnh dáng đứng.'
      ],
      stepImages: [
        'assets/images/Dragon/origami-dragonfly-paper-fold-step-1.jpg',
        'assets/images/Dragon/origami-dragonfly-paper-fold-step-2.jpg',
        'assets/images/Dragon/origami-dragonfly-paper-fold-step-3.mp4',
        'assets/images/Dragon/origami-dragonfly-paper-fold-step-4.png',
        'assets/images/Dragon/origami-dragonfly-paper-fold-step-5.mp4',
        'assets/images/Dragon/origami-dragonfly-paper-fold-step-6.jpg',
        'assets/images/Dragon/origami-dragonfly-paper-fold-step-7.png',
        'assets/images/Dragon/origami-dragonfly-paper-fold-step-8.mp4',
        'assets/images/Dragon/origami-dragonfly-paper-fold-step-9.mp4',
        'assets/images/Dragon/origami-dragonfly-paper-fold-step-10.mp4',
        'assets/images/Dragon/origami-dragonfly-paper-fold-step-11.gif',
        'assets/images/Dragon/origami-dragonfly-paper-fold-step-12.png',
        'assets/images/Dragon/origami-dragonfly-paper-fold-step-13.mp4',
        'assets/images/Dragon/origami-dragonfly-paper-fold-step-14.mp4',
        'assets/images/Dragon/origami-dragonfly-paper-fold-step-15.mp4',
        'assets/images/Dragon/origami-dragonfly-paper-fold-step-16.png',
        'assets/images/Dragon/origami-dragonfly-paper-fold-step-17.mp4'
      ],
      stepDiagrams: [
        'assets/images/Dragon/origami-dragonfly-diagram-step-1-1536x1536.jpg',
        'assets/images/Dragon/origami-dragonfly-diagram-step-2-1536x1536.jpg',
        'assets/images/Dragon/origami-dragonfly-diagram-step-3-1536x1536.jpg',
        'assets/images/Dragon/origami-dragonfly-diagram-step-4-1536x1536.jpg',
        'assets/images/Dragon/origami-dragonfly-diagram-step-5-1536x1536.jpg',
        'assets/images/Dragon/origami-dragonfly-diagram-step-6-1536x1536.jpg',
        'assets/images/Dragon/origami-dragonfly-diagram-step-7-1536x1536.jpg',
        'assets/images/Dragon/origami-dragonfly-diagram-step-8-1536x1536.jpg',
        'assets/images/Dragon/origami-dragonfly-diagram-step-9-1536x1536.jpg',
        'assets/images/Dragon/origami-dragonfly-diagram-step-10-1536x1536.jpg',
        'assets/images/Dragon/origami-dragonfly-diagram-step-11-1536x1536.jpg',
        'assets/images/Dragon/origami-dragonfly-diagram-step-12-1536x1536.jpg',
        'assets/images/Dragon/origami-dragonfly-diagram-step-13-1536x1536.jpg',
        'assets/images/Dragon/origami-dragonfly-diagram-step-14-1536x1536.jpg',
        'assets/images/Dragon/origami-dragonfly-diagram-step-15-1536x1536.jpg',
        'assets/images/Dragon/origami-dragonfly-diagram-step-16-1536x1536.jpg',
        'assets/images/Dragon/origami-dragonfly-diagram-step-17-1536x1536.jpg'
      ],
      currentStep: 0,
    ),
    OrigamiModel(
      id: 4,
      title: 'Cáo Giấy Cute',
      category: 'Động vật',
      difficulty: 2,
      stepsCount: 8,
      timeEstimate: '5 phút',
      description: 'Mẫu gấp con cáo nhỏ đáng yêu với đuôi xòe, thích hợp để trang trí bàn học.',
      imagePath: 'assets/images/Fox/Cover.png',
      videoTutorial: 'assets/images/Fox/Tutorial-Fox-Origami.mp4',
      steps: [
        'Gấp đôi tờ giấy hình vuông theo đường chéo để tạo hình tam giác.',
        'Gập đôi hình tam giác rồi mở ra lấy nếp gấp ở trục giữa.',
        'Gấp hai góc nhọn dưới bên trái và phải lên trên để gặp góc nhọn đỉnh.',
        'Gập đôi toàn bộ mô hình theo chiều dọc từ trái sang phải.',
        'Xoay mô hình góc 90 độ sao cho phần mép mở hướng lên trên.',
        'Gập lớp giấy phía ngoài cùng xuống dưới sang bên phải để tạo tai cáo thứ nhất.',
        'Gập lớp giấy ở giữa sang bên trái để định hình phần đầu và mũi cáo.',
        'Gập lớp giấy trong cùng sang trái tạo tai cáo thứ hai, vuốt đáy để cáo tự đứng vững.'
      ],
      stepImages: [
        'assets/images/Fox/origami-fox-step-1-paper-fold-edited.jpg',
        'assets/images/Fox/origami-fox-step-2-paper-fold.jpg',
        'assets/images/Fox/origami-fox-step-3-paper-fold.jpg',
        'assets/images/Fox/origami-fox-paper-fold-step-4.gif',
        'assets/images/Fox/origami-fox-paper-fold-step-5.gif',
        'assets/images/Fox/origami-fox-step-6-paper-fold.jpg',
        'assets/images/Fox/origami-fox-paper-fold-step-7.mp4',
        'assets/images/Fox/origami-fox-step-8-paper-fold.jpg'
      ],
      stepDiagrams: [
        'assets/images/Fox/Traditional-Origami-Fox-Diagram-Step-1.jpg',
        'assets/images/Fox/Traditional-Origami-Fox-Diagram-Step-2.jpg',
        'assets/images/Fox/Traditional-Origami-Fox-Diagram-Step-3.jpg',
        'assets/images/Fox/Traditional-Origami-Fox-Diagram-Step-4.jpg',
        'assets/images/Fox/Traditional-Origami-Fox-Diagram-Step-5.jpg',
        'assets/images/Fox/Traditional-Origami-Fox-Diagram-Step-6.jpg',
        'assets/images/Fox/Traditional-Origami-Fox-Diagram-Step-7.jpg',
        'assets/images/Fox/Traditional-Origami-Fox-Diagram-Step-8.jpg'
      ],
      currentStep: 0,
    ),
    OrigamiModel(
      id: 5,
      title: 'Chim Thiên Nga',
      category: 'Động vật',
      difficulty: 2,
      stepsCount: 8,
      timeEstimate: '6 phút',
      description: 'Mẫu gấp thiên nga với chiếc cổ dài kiêu hãnh và đôi cánh xếp nếp tinh tế.',
      imagePath: 'assets/images/Swan/Cover.png',
      videoTutorial: 'assets/images/Swan/Tutorial Origami Swan.mp4',
      steps: [
        'Đặt mặt trắng của giấy hướng lên. Gấp đôi theo đường chéo tạo nếp chữ X rồi mở ra.',
        'Gấp hai mép dưới trái và phải sát vào đường chéo giữa (Kite Base).',
        'Lật mặt sau. Gấp tiếp hai mép bên vào sát đường chéo để thân thiên nga thon nhỏ lại.',
        'Gập góc nhọn dài phía dưới lên phía đỉnh đối diện.',
        'Gập một góc nhỏ ở đầu nhọn ngược xuống dưới để tạo hình đầu thiên nga.',
        'Gập đôi toàn bộ mô hình theo chiều dọc từ dưới lên trên.',
        'Kéo phần cổ thiên nga hướng lên trên chếch ra ngoài, vuốt nếp gấp ở gốc cổ.',
        'Kéo nhẹ phần đầu thiên nga hướng lên, định hình mỏ để hoàn thành thiên nga.'
      ],
      stepImages: [
        'assets/images/Swan/origami-swan-paper-fold-step-1.jpg',
        'assets/images/Swan/origami-swan-paper-fold-step-2.jpg',
        'assets/images/Swan/origami-swan-paper-fold-step-3.jpg',
        'assets/images/Swan/origami-swan-paper-fold-step-4-2.gif',
        'assets/images/Swan/origami-swan-paper-fold-step-5.gif',
        'assets/images/Swan/origami-swan-paper-fold-step-6.gif',
        'assets/images/Swan/origami-swan-paper-fold-step-7.gif',
        'assets/images/Swan/origami-swan-paper-fold-step-8.gif'
      ],
      stepDiagrams: [
        'assets/images/Swan/Traditional-Origami-Swan-Diagram-Step-1-edited.jpg',
        'assets/images/Swan/origami-swan-diagram-step-2-1.jpg',
        'assets/images/Swan/origami-swan-diagram-step-3.jpg',
        'assets/images/Swan/origami-swan-diagram-step-4.jpg',
        'assets/images/Swan/origami-swan-diagram-step-5.jpg',
        'assets/images/Swan/origami-swan-diagram-step-6.jpg',
        'assets/images/Swan/origami-swan-diagram-step-7.jpg',
        'assets/images/Swan/origami-swan-diagram-step-8.jpg'
      ],
      currentStep: 0,
    ),
    OrigamiModel(
      id: 6,
      title: 'Hoa Tulip',
      category: 'Hoa',
      difficulty: 2,
      stepsCount: 14,
      timeEstimate: '5 phút',
      description: 'Bông hoa tulip mùa xuân nở rộ duyên dáng với cành lá xanh mướt.',
      imagePath: 'assets/images/Tulip/Cover.png',
      videoTutorial: 'assets/images/Tulip/Origami Tulip Tutorial  Step-by-Step Instructions.mp4',
      steps: [
        'Gấp đôi tờ giấy theo chiều ngang và dọc tạo nếp chữ thập rồi mở ra.',
        'Lật giấy. Gấp đôi chéo 2 bên tạo nếp chữ X rồi mở ra.',
        'Túm mép thu gọn giấy thành hình tam giác hai lớp (Waterbomb Base).',
        'Gấp góc dưới bên trái và phải hướng lên góc đỉnh ở cả mặt trước và mặt sau.',
        'Gấp cánh bên phải sang trái ở lớp trước, lặp lại cho lớp sau.',
        'Gập góc trái và phải đè lên nhau hơi lệch qua trục giữa ở mặt trước.',
        'Luồn một góc giấy vào trong túi của góc kia để khóa chặt cánh hoa lại.',
        'Lặp lại bước 6 và 7 cho mặt giấy phía sau.',
        'Thổi nhẹ vào lỗ nhỏ ở phần đáy bông hoa để làm phồng tulip thành khối 3D.',
        'Nhẹ nhàng bẻ ngược 4 cánh hoa bên trên xuôi xuống để hoa tulip nở.',
        'Lấy tờ giấy màu xanh làm cành. Gấp đôi chéo để lấy nếp gấp giữa.',
        'Gấp hai mép góc sát vào nếp giữa tạo hình chiếc diều.',
        'Gấp mép bên sát vào đường giữa một lần nữa, sau đó gập đôi dọc lại.',
        'Bẻ nghiêng phần dưới cắm hoa làm lá cành, luồn đầu cành vào đáy hoa tulip.'
      ],
      stepImages: [
        'assets/images/Tulip/origami-tulip-paper-fold-step-1.jpg',
        'assets/images/Tulip/origami-tulip-paper-fold-step-2.jpg',
        'assets/images/Tulip/origami-tulip-paper-fold-step-3.jpg',
        'assets/images/Tulip/origami-tulip-paper-fold-step-4.jpg',
        'assets/images/Tulip/origami-tulip-paper-fold-step-5.gif',
        'assets/images/Tulip/origami-tulip-paper-fold-step-6.jpg',
        'assets/images/Tulip/origami-tulip-paper-fold-step-7.jpg',
        'assets/images/Tulip/origami-tulip-paper-fold-step-8.mp4',
        'assets/images/Tulip/origami-tulip-paper-fold-step-9.jpg',
        'assets/images/Tulip/origami-tulip-paper-fold-step-10.mp4',
        'assets/images/Tulip/origami-tulip-paper-fold-step-11.jpg',
        'assets/images/Tulip/origami-tulip-paper-fold-step-12.jpg',
        'assets/images/Tulip/origami-tulip-paper-fold-step-13.jpg',
        'assets/images/Tulip/origami-tulip-paper-fold-step-14.mp4'
      ],
      stepDiagrams: [
        'assets/images/Tulip/Traditional-Origami-Tulip-Diagram-step-1.jpg',
        'assets/images/Tulip/Traditional-Origami-Tulip-Diagram-step-2.jpg',
        'assets/images/Tulip/Traditional-Origami-Tulip-Diagram-step-3.jpg',
        'assets/images/Tulip/Traditional-Origami-Tulip-Diagram-step-4.jpg',
        'assets/images/Tulip/Traditional-Origami-Tulip-Diagram-step-5.jpg',
        'assets/images/Tulip/Traditional-Origami-Tulip-Diagram-step-6.jpg',
        'assets/images/Tulip/Traditional-Origami-Tulip-Diagram-step-7.jpg',
        'assets/images/Tulip/Traditional-Origami-Tulip-Diagram-step-8.jpg',
        'assets/images/Tulip/Traditional-Origami-Tulip-Diagram-step-9.jpg',
        'assets/images/Tulip/Traditional-Origami-Tulip-Diagram-step-10.jpg',
        'assets/images/Tulip/Traditional-Origami-Tulip-Diagram-step-11.jpg',
        'assets/images/Tulip/Traditional-Origami-Tulip-Diagram-step-12.jpg',
        'assets/images/Tulip/Traditional-Origami-Tulip-Diagram-step-13.jpg',
        'assets/images/Tulip/Traditional-Origami-Tulip-Diagram-step-14.jpg'
      ],
      currentStep: 0,
    ),
    OrigamiModel(
      id: 7,
      title: 'Cá Thần Tiên',
      category: 'Động vật',
      difficulty: 2,
      stepsCount: 7,
      timeEstimate: '5 phút',
      description: 'Mẫu gấp cá thần tiên (Angelfish) dẹt hai bên với vây dài thướt tha rất ngộ nghĩnh.',
      imagePath: 'assets/images/Angle Fish/Cover.png',
      videoTutorial: null,
      steps: [
        'Gấp chéo chập và gấp ngang dọc để tạo đầy đủ các nếp gấp phụ.',
        'Gấp 4 góc của tờ giấy vào điểm tâm chính giữa rồi mở ra lấy nếp gấp hình vuông.',
        'Thu dẹt giấy lại thành hình tam giác hai lớp (Waterbomb Base).',
        'Gập mép dưới bên phải của lớp giấy phía trên sát trùng vào trục nếp giữa.',
        'Gập mép dưới bên trái đè chéo đè lên lớp vây bên phải vừa gấp để tạo đuôi cá chéo.',
        'Lật ngược chú cá ra mặt sau. Gấp hai góc nhọn bên hông sát vào đường giữa.',
        'Định hình lại các vây bên hông và vây đuôi để hoàn thành chú cá thần tiên.'
      ],
      stepImages: [
        'assets/images/Angle Fish/origami-angelfish-paper-fold-step-1.png',
        'assets/images/Angle Fish/origami-angelfish-paper-fold-step-2.gif',
        'assets/images/Angle Fish/origami-angelfish-paper-fold-step-3.png',
        'assets/images/Angle Fish/origami-angelfish-paper-fold-step-4.mp4',
        'assets/images/Angle Fish/origami-angelfish-paper-fold-step-5.mp4',
        'assets/images/Angle Fish/origami-angelfish-paper-fold-step-6.mp4',
        'assets/images/Angle Fish/origami-angelfish-paper-fold-step-7.gif'
      ],
      stepDiagrams: [
        'assets/images/Angle Fish/origami-angelfish-diagram-step-1.png',
        'assets/images/Angle Fish/origami-angelfish-diagram-step-2.png',
        'assets/images/Angle Fish/origami-angelfish-diagram-step-3.png',
        'assets/images/Angle Fish/origami-angelfish-diagram-step-4.png',
        'assets/images/Angle Fish/origami-angelfish-diagram-step-5.png',
        'assets/images/Angle Fish/origami-angelfish-diagram-step-6.png',
        'assets/images/Angle Fish/origami-angelfish-diagram-step-7.png'
      ],
      currentStep: 0,
    ),
    OrigamiModel(
      id: 8,
      title: 'Cá Vàng Đáng Yêu',
      category: 'Động vật',
      difficulty: 1,
      stepsCount: 8,
      timeEstimate: '4 phút',
      description: 'Mẫu gấp chú cá bơi lội ngộ nghĩnh, cực kỳ đơn giản cho người mới bắt đầu học gấp giấy.',
      imagePath: 'assets/images/Fish/Cover.png',
      videoTutorial: null,
      steps: [
        'Gấp chéo tờ giấy theo 2 đường chéo để tạo nếp hình chữ X rồi mở ra.',
        'Gấp mép góc trái và phải vào sát trùng khớp đường chéo giữa.',
        'Gấp tiếp góc đỉnh trên và góc nhọn dưới vào đường chéo giữa để tạo hình thoi.',
        'Mở lật các mép giấy tam giác trên và dưới ra lại.',
        'Nhẹ nhàng kéo phần giấy ẩn bên trong vây ra ngoài để tạo hai vây cá đối xứng.',
        'Gấp đôi toàn bộ mô hình cá lại theo chiều ngang.',
        'Gấp ngược góc nhọn đuôi hướng chếch lên trên tạo hình vây đuôi cá.',
        'Định hình hai vây bơi mở sang hai bên để chú cá vàng hoàn thiện dáng bơi.'
      ],
      stepImages: [
        'assets/images/Fish/origami-fish-paper-fold-step-1.jpg',
        'assets/images/Fish/origami-fish-paper-fold-step-2-edited.jpg',
        'assets/images/Fish/origami-fish-paper-fold-step-3.jpg',
        'assets/images/Fish/origami-fish-paper-fold-step-4.jpg',
        'assets/images/Fish/origami-fish-paper-fold-step-5.jpg',
        'assets/images/Fish/origami-fish-paper-fold-step-6.jpg',
        'assets/images/Fish/origami-fish-paper-fold-step-7.jpg',
        'assets/images/Fish/origami-fish-paper-fold-step-8.jpg'
      ],
      stepDiagrams: [
        'assets/images/Fish/Traditional-Origami-Fish-Diagram-step-1.jpg',
        'assets/images/Fish/Traditional-Origami-Fish-Diagram-step-2.jpg',
        'assets/images/Fish/Traditional-Origami-Fish-Diagram-step-3.jpg',
        'assets/images/Fish/Traditional-Origami-Fish-Diagram-step-4.jpg',
        'assets/images/Fish/Traditional-Origami-Fish-Diagram-step-5.jpg',
        'assets/images/Fish/Traditional-Origami-Fish-Diagram-step-6.jpg',
        'assets/images/Fish/Traditional-Origami-Fish-Diagram-step-7.jpg',
        'assets/images/Fish/Traditional-Origami-Fish-Diagram-step-8.jpg'
      ],
      currentStep: 0,
    ),
    OrigamiModel(
      id: 9,
      title: 'Đông Tây Nam Bắc',
      category: 'Đồ vật',
      difficulty: 1,
      stepsCount: 11,
      timeEstimate: '3 phút',
      description: 'Trò chơi gấp giấy bói toán tuổi thơ quen thuộc, dễ gấp và mang tính giải trí cao.',
      imagePath: 'assets/images/Fortune Teller/Cover.png',
      videoTutorial: 'assets/images/Fortune Teller/Paper-Fortune-Teller-Tutorial-Step.mp4',
      steps: [
        'Gấp chéo tờ giấy hình vuông cả hai bên tạo nếp chéo và mở ra.',
        'Gập cả bốn góc nhọn của tờ giấy hướng sát vào điểm tâm chính giữa (Blintz Fold).',
        'Lật ngược tờ giấy ra phía mặt sau.',
        'Gập tiếp cả bốn góc của mặt sau này hướng sát vào tâm chính giữa một lần nữa.',
        'Gấp đôi hình vuông theo chiều ngang rồi mở ra, gấp tiếp chiều dọc rồi mở ra để giấy mềm.',
        'Luồn các đầu ngón tay vào 4 túi giấy trống mở dẹt ở phía dưới.',
        'Dùng ngón tay cái và ngón trỏ của hai tay chụm lại để bật các góc hướng lên.',
        'Viết số từ 1 đến 8 vào các mặt tam giác gấp bên trong.',
        'Viết tên các màu sắc hoặc hướng (Đông, Tây, Nam, Bắc) vào bốn cánh giấy bên ngoài.',
        'Viết các lời chúc/lời bói vui nhộn ẩn dưới các ô số ở lớp giấy trong.',
        'Luồn tay cử động mở đóng theo nhịp dọc và ngang để chơi bói toán cùng bạn bè!'
      ],
      stepImages: [
        'assets/images/Fortune Teller/origami-fortune-teller-paper-fold-step-1.jpg',
        'assets/images/Fortune Teller/origami-fortune-teller-paper-fold-step-2.jpg',
        'assets/images/Fortune Teller/origami-fortune-teller-paper-fold-step-3.jpg',
        'assets/images/Fortune Teller/origami-fortune-teller-paper-fold-step-4.gif',
        'assets/images/Fortune Teller/origami-fortune-teller-paper-fold-step-5.jpg',
        'assets/images/Fortune Teller/origami-fortune-teller-paper-fold-step-6.jpg',
        'assets/images/Fortune Teller/origami-fortune-teller-paper-fold-step-7.mp4',
        'assets/images/Fortune Teller/origami-fortune-teller-paper-fold-step-8.mp4',
        'assets/images/Fortune Teller/origami-fortune-teller-paper-fold-step-9.mp4',
        'assets/images/Fortune Teller/origami-fortune-teller-paper-fold-step-10.jpg',
        'assets/images/Fortune Teller/origami-fortune-teller-paper-fold-step-11.mp4'
      ],
      stepDiagrams: [
        'assets/images/Fortune Teller/origami-fortune-teller-diagram-step-1-1536x1536.png',
        'assets/images/Fortune Teller/origami-fortune-teller-diagram-step-2-1536x1536.png',
        'assets/images/Fortune Teller/origami-fortune-teller-diagram-step-3-1536x1536.png',
        'assets/images/Fortune Teller/origami-fortune-teller-diagram-step-4-1536x1536.png',
        'assets/images/Fortune Teller/origami-fortune-teller-diagram-step-5-1536x1536.png',
        'assets/images/Fortune Teller/origami-fortune-teller-diagram-step-6-1536x1536.png',
        'assets/images/Fortune Teller/origami-fortune-teller-diagram-step-7-1536x1536.png',
        'assets/images/Fortune Teller/origami-fortune-teller-diagram-step-8-1536x1536.png',
        'assets/images/Fortune Teller/origami-fortune-teller-diagram-step-9-1536x1536.png',
        'assets/images/Fortune Teller/origami-fortune-teller-diagram-step-10-1536x1536.png',
        'assets/images/Fortune Teller/origami-fortune-teller-diagram-step-11-1536x1536.png'
      ],
      currentStep: 0,
    ),
    OrigamiModel(
      id: 10,
      title: 'Hoa Hồng Tình Yêu',
      category: 'Hoa',
      difficulty: 3,
      stepsCount: 9,
      timeEstimate: '10 phút',
      description: 'Mẫu gấp bông hoa hồng nở rộ quyến rũ, thích hợp để làm quà tặng hoặc trang trí.',
      imagePath: 'assets/images/Rose/Cover.png',
      videoTutorial: 'assets/images/Rose/Tutorial-Origami-Rose.mp4',
      steps: [
        'Bắt đầu với mặt trắng hướng lên. Gấp đôi tờ giấy theo chiều dọc và ngang, sau đó mở ra lấy nếp gấp chữ thập.',
        'Gập cả bốn góc của tờ giấy hướng vào điểm tâm chính giữa (Blintz fold).',
        'Tiếp tục gập bốn góc nhọn của hình vuông mới vào điểm tâm thêm một lần nữa.',
        'Gập cả bốn góc nhọn vào điểm tâm chính giữa lần thứ ba (lần cuối cùng).',
        'Gập lớp giấy ngoài cùng của mỗi cánh hướng ra phía ngoài để tạo thành hàng cánh hoa thứ nhất.',
        'Để tạo hàng cánh hoa thứ hai, gập đôi mỗi cánh vuông nhỏ bên trong ra ngoài trùng với lớp cánh trước.',
        'Lặp lại thao tác tương tự cho lớp cánh hoa hồng thứ ba ở trong cùng.',
        'Gấp ngược bốn góc vuông nhọn ngoài cùng ra mặt sau của bông hoa (Mountain fold).',
        'Nhẹ nhàng uốn cong cánh hoa hồng ra phía ngoài bằng đầu ngón tay để tạo dáng hoa nở tự nhiên.'
      ],
      stepImages: [
        'assets/images/Rose/origami-rose-paper-fold-step-1.png',
        'assets/images/Rose/origami-rose-paper-fold-step-2.png',
        'assets/images/Rose/origami-rose-paper-fold-step-3.png',
        'assets/images/Rose/origami-rose-paper-fold-step-4.png',
        'assets/images/Rose/origami-rose-paper-fold-step-5.png',
        'assets/images/Rose/origami-rose-paper-fold-step-6.png',
        'assets/images/Rose/origami-rose-paper-fold-step-7.png',
        'assets/images/Rose/origami-rose-paper-fold-step-8.png',
        'assets/images/Rose/origami-rose-paper-fold-step-9.png'
      ],
      stepDiagrams: [
        'assets/images/Rose/Traditional-Fractal-Rose-Diagram-Step-1.png',
        'assets/images/Rose/Traditional-Fractal-Rose-Diagram-Step-3.png',
        'assets/images/Rose/Traditional-Fractal-Rose-Diagram-Step-3.png',
        'assets/images/Rose/Traditional-Fractal-Rose-Diagram-Step-4.png',
        'assets/images/Rose/Traditional-Fractal-Rose-Diagram-Step-5.png',
        'assets/images/Rose/Traditional-Fractal-Rose-Diagram-Step-6.png',
        'assets/images/Rose/Traditional-Fractal-Rose-Diagram-Step-7.png',
        'assets/images/Rose/Traditional-Fractal-Rose-Diagram-Step-8.png',
        'assets/images/Rose/Traditional-Fractal-Rose-Diagram-Step-9.png'
      ],
      currentStep: 0,
    ),
  ];
}
